spring:
  profiles:
    active: local
  application:
    name: server

server:
  port: 8081

---

spring:
  profiles: local, development
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb

---

spring:
  profiles: production