spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin